#!/usr/bin/env python3
"""Compute oracle expert-path efficiency and visualize potential savings."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def bootstrap_ci(values: np.ndarray, num_samples: int, confidence: float, rng: np.random.Generator) -> tuple[float, float]:
    if len(values) == 0:
        return float("nan"), float("nan")
    stats = []
    for _ in range(num_samples):
        sample = rng.choice(values, size=len(values), replace=True)
        stats.append(sample.mean())
    lower = np.percentile(stats, (1 - confidence) / 2 * 100)
    upper = np.percentile(stats, (1 + confidence) / 2 * 100)
    return float(lower), float(upper)


def ensure_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(description="Oracle efficiency analysis")
    parser.add_argument("waves", type=Path, help="CSV generated by analyze_tree_experts")
    parser.add_argument("--out-prefix", type=Path, default=Path("results/combined/oracle_efficiency"))
    parser.add_argument("--num-bootstrap", type=int, default=1000)
    parser.add_argument("--confidence", type=float, default=0.95)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    df = pd.read_csv(args.waves)
    df = df.copy()

    denom = df["total_unique_all"].replace(0, np.nan)
    df["oracle_ratio"] = df["accepted_unique_total"] / denom
    df["oracle_savings"] = 1.0 - df["oracle_ratio"]
    df = df.dropna(subset=["oracle_ratio"])

    def assign_bucket(value: float) -> str:
        if value <= 2:
            return "len≤2"
        if value <= 4:
            return "len3-4"
        if value <= 6:
            return "len5-6"
        return "len≥7"

    df["accept_len_bucket"] = df["accepted_len"].apply(assign_bucket)
    bucket_order = ["len≤2", "len3-4", "len5-6", "len≥7"]

    rng = np.random.default_rng(args.seed)

    summary_rows = []
    for dataset, group in df.groupby("dataset"):
        values = group["oracle_ratio"].to_numpy()
        savings = group["oracle_savings"].to_numpy()

        ratio_ci = bootstrap_ci(values, args.num_bootstrap, args.confidence, rng)
        savings_ci = bootstrap_ci(savings, args.num_bootstrap, args.confidence, rng)

        summary_rows.append(
            {
                "dataset": dataset,
                "count": len(group),
                "oracle_ratio_mean": float(np.mean(values)),
                "oracle_ratio_ci_lo": ratio_ci[0],
                "oracle_ratio_ci_hi": ratio_ci[1],
                "oracle_savings_mean": float(np.mean(savings)),
                "oracle_savings_ci_lo": savings_ci[0],
                "oracle_savings_ci_hi": savings_ci[1],
            }
        )

    summary = pd.DataFrame(summary_rows).sort_values("dataset").reset_index(drop=True)

    bucket_rows = []
    for (dataset, bucket), group in df.groupby(["dataset", "accept_len_bucket"], sort=False):
        values = group["oracle_ratio"].to_numpy()
        savings = group["oracle_savings"].to_numpy()
        ratio_ci = bootstrap_ci(values, args.num_bootstrap, args.confidence, rng)
        savings_ci = bootstrap_ci(savings, args.num_bootstrap, args.confidence, rng)
        bucket_rows.append(
            {
                "dataset": dataset,
                "accept_len_bucket": bucket,
                "count": len(group),
                "oracle_ratio_mean": float(np.mean(values)),
                "oracle_ratio_ci_lo": ratio_ci[0],
                "oracle_ratio_ci_hi": ratio_ci[1],
                "oracle_savings_mean": float(np.mean(savings)),
                "oracle_savings_ci_lo": savings_ci[0],
                "oracle_savings_ci_hi": savings_ci[1],
            }
        )

    bucket_summary = (
        pd.DataFrame(bucket_rows)
        .sort_values(["dataset", "accept_len_bucket"], key=lambda col: col.map({k: i for i, k in enumerate(bucket_order)}) if col.name == "accept_len_bucket" else col)
        .reset_index(drop=True)
    )

    out_prefix = args.out_prefix
    ensure_dir(out_prefix)
    summary_path = out_prefix.with_suffix(".csv")
    summary.to_csv(summary_path, index=False)
    bucket_path = out_prefix.with_name(out_prefix.stem + "_by_bucket.csv")
    bucket_summary.to_csv(bucket_path, index=False)

    # Histogram / KDE
    fig, ax = plt.subplots(figsize=(6, 4))
    for idx, (dataset, group) in enumerate(df.groupby("dataset")):
        ax.hist(
            group["oracle_ratio"],
            bins=20,
            alpha=0.4,
            label=f"{dataset} (mean={group['oracle_ratio'].mean():.3f})",
            color=f"C{idx}",
        )
    ax.set_xlabel("Oracle ratio (accepted experts / total experts)")
    ax.set_ylabel("Cycle count")
    ax.set_title("Oracle efficiency distribution")
    ax.legend()
    fig.tight_layout()
    histogram_path = out_prefix.with_name(out_prefix.stem + "_hist.png")
    fig.savefig(histogram_path)
    plt.close(fig)

    # Bucketed histograms
    fig, axes = plt.subplots(len(bucket_order), 1, figsize=(6, 3 * len(bucket_order)), sharex=True)
    if len(bucket_order) == 1:
        axes = [axes]
    for idx, bucket in enumerate(bucket_order):
        ax = axes[idx]
        bucket_df = df[df["accept_len_bucket"] == bucket]
        if bucket_df.empty:
            ax.text(0.5, 0.5, "No data", ha="center", va="center")
            ax.set_axis_off()
            continue
        for ds_idx, (dataset, group) in enumerate(bucket_df.groupby("dataset")):
            ax.hist(
                group["oracle_ratio"],
                bins=20,
                alpha=0.4,
                label=f"{dataset} (n={len(group)})",
                color=f"C{ds_idx}",
            )
        ax.set_ylabel(f"{bucket}")
        ax.legend()
    axes[-1].set_xlabel("Oracle ratio (accepted experts / total experts)")
    fig.suptitle("Oracle efficiency by accepted length bucket")
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    bucket_hist_path = out_prefix.with_name(out_prefix.stem + "_hist_by_bucket.png")
    fig.savefig(bucket_hist_path)
    plt.close(fig)

    # Bar chart of potential savings
    fig, ax = plt.subplots(figsize=(5, 4))
    positions = np.arange(len(summary))
    ax.bar(
        positions,
        summary["oracle_savings_mean"],
        color=[f"C{i}" for i in range(len(summary))],
        alpha=0.6,
    )
    ax.errorbar(
        positions,
        summary["oracle_savings_mean"],
        yerr=[
            summary["oracle_savings_mean"] - summary["oracle_savings_ci_lo"],
            summary["oracle_savings_ci_hi"] - summary["oracle_savings_mean"],
        ],
        fmt="none",
        color="black",
        capsize=4,
    )
    ax.set_xticks(positions)
    ax.set_xticklabels(summary["dataset"])
    ax.set_ylabel("Potential savings (1 - oracle ratio)")
    ax.set_ylim(0, max(0.05, summary["oracle_savings_ci_hi"].max() * 1.1))
    ax.set_title("Theoretical expert savings with oracle path")
    fig.tight_layout()
    bar_path = out_prefix.with_name(out_prefix.stem + "_savings.png")
    fig.savefig(bar_path)
    plt.close(fig)

    print("Oracle efficiency summary written to", summary_path)
    print("Bucketed summary written to", bucket_path)


if __name__ == "__main__":
    main()
